language: go
dist: trusty
sudo: required
go:
- 1.8
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
install:
- go get .
script:
- go test -covermode=count -coverprofile=profile.cov
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -repotoken bR2qmLHQEYkCRTYdW2S9kYwz2dcRgn6zW
before_deploy:
- make version
- python setup.py egg_info
deploy:
  provider: pypi
  skip_cleanup: true
  skip_upload_docs: true
  user: piotrkowalczuk
  password:
    secure: d+s2QH+AoA+eflfRniMib0AcbwHynK+Oxw4I2KKb1vpQYQYZ8Ks/e0eNEhAxasmwNjrtYr6D14NgWlRwcTy7oZFi0M6dNX8oBH5HH2w5yGtnsuGuBT8qT9SU4/F3hoAyBTZa9V3+HqFeXtiX2Ye5wKIKiTV9L8rIa/fHV5ab8qqlA9QHupWjunxjNXTmiFuSXSJbB1jXJNJQsFw/GBy6kUtz2KApBkUCuiGnuO6MP5oMWt1B1LGbwegEkBQE57uaAKEQrtVJwTu/8aPf/Sh3WBbo4M/hET1zJj8fqvjEZkieDSbxVxIZw300A5840e/z1coVD0w9mGOCCozlsgR+HHHv9Cu2EjQLECcIPnS7WL/as3K2WlsrUn4RGlD2JjDdMhs5RmKrqzTUhxF848BZH5WwWPYiBzFCgzC1GDTGlJq8rTZOroRSpvb2zJQM2GUlS6gM2b3b1KQnVTdJGMGfGLWuXRALAJ+GMhi/l6LgeN4gQUSdLfvvyU1aWDIqvhI7Ck+ahY58LPAGRvsqqKzbwEaoCeu10psfQbhW59g/rAPY4cMj/EOccca7bKTI3zc0+zTiiKtUGZveaJrn9kbzvi8abvIHFUycMtv3WICq4ZbBDVcuvJ8J5L5+v8g5NopLRHoVGiY8zquo85SnUJnJ2AjTalA3npt1yVQ91Osm8vU=
  on:
    tags: true
