// Code generated by protoc-gen-go.
// source: qtypes.proto
// DO NOT EDIT!

/*
Package qtypes is a generated protocol buffer package.

It is generated from these files:
	qtypes.proto

It has these top-level messages:
	String
	Int64
	Uint64
	Float64
	Timestamp
*/
package qtypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryType int32

const (
	QueryType_NULL             QueryType = 0
	QueryType_EQUAL            QueryType = 1
	QueryType_GREATER          QueryType = 2
	QueryType_GREATER_EQUAL    QueryType = 3
	QueryType_LESS             QueryType = 4
	QueryType_LESS_EQUAL       QueryType = 5
	QueryType_IN               QueryType = 6
	QueryType_BETWEEN          QueryType = 7
	QueryType_HAS_PREFIX       QueryType = 8
	QueryType_HAS_SUFFIX       QueryType = 9
	QueryType_SUBSTRING        QueryType = 10
	QueryType_PATTERN          QueryType = 11
	QueryType_MIN_LENGTH       QueryType = 12
	QueryType_MAX_LENGTH       QueryType = 13
	QueryType_OVERLAP          QueryType = 14
	QueryType_CONTAINS         QueryType = 15
	QueryType_IS_CONTAINED_BY  QueryType = 16
	QueryType_HAS_ELEMENT      QueryType = 17
	QueryType_HAS_ANY_ELEMENT  QueryType = 18
	QueryType_HAS_ALL_ELEMENTS QueryType = 19
)

var QueryType_name = map[int32]string{
	0:  "NULL",
	1:  "EQUAL",
	2:  "GREATER",
	3:  "GREATER_EQUAL",
	4:  "LESS",
	5:  "LESS_EQUAL",
	6:  "IN",
	7:  "BETWEEN",
	8:  "HAS_PREFIX",
	9:  "HAS_SUFFIX",
	10: "SUBSTRING",
	11: "PATTERN",
	12: "MIN_LENGTH",
	13: "MAX_LENGTH",
	14: "OVERLAP",
	15: "CONTAINS",
	16: "IS_CONTAINED_BY",
	17: "HAS_ELEMENT",
	18: "HAS_ANY_ELEMENT",
	19: "HAS_ALL_ELEMENTS",
}
var QueryType_value = map[string]int32{
	"NULL":             0,
	"EQUAL":            1,
	"GREATER":          2,
	"GREATER_EQUAL":    3,
	"LESS":             4,
	"LESS_EQUAL":       5,
	"IN":               6,
	"BETWEEN":          7,
	"HAS_PREFIX":       8,
	"HAS_SUFFIX":       9,
	"SUBSTRING":        10,
	"PATTERN":          11,
	"MIN_LENGTH":       12,
	"MAX_LENGTH":       13,
	"OVERLAP":          14,
	"CONTAINS":         15,
	"IS_CONTAINED_BY":  16,
	"HAS_ELEMENT":      17,
	"HAS_ANY_ELEMENT":  18,
	"HAS_ALL_ELEMENTS": 19,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// String ...
type String struct {
	Values      []string  `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Valid       bool      `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Negation    bool      `protobuf:"varint,3,opt,name=negation" json:"negation,omitempty"`
	Type        QueryType `protobuf:"varint,4,opt,name=type,enum=qtypes.QueryType" json:"type,omitempty"`
	Insensitive bool      `protobuf:"varint,5,opt,name=insensitive" json:"insensitive,omitempty"`
}

func (m *String) Reset()                    { *m = String{} }
func (m *String) String() string            { return proto.CompactTextString(m) }
func (*String) ProtoMessage()               {}
func (*String) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *String) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *String) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *String) GetNegation() bool {
	if m != nil {
		return m.Negation
	}
	return false
}

func (m *String) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_NULL
}

func (m *String) GetInsensitive() bool {
	if m != nil {
		return m.Insensitive
	}
	return false
}

// Int64 ...
type Int64 struct {
	Values   []int64   `protobuf:"varint,1,rep,packed,name=values" json:"values,omitempty"`
	Valid    bool      `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Negation bool      `protobuf:"varint,3,opt,name=negation" json:"negation,omitempty"`
	Type     QueryType `protobuf:"varint,4,opt,name=type,enum=qtypes.QueryType" json:"type,omitempty"`
}

func (m *Int64) Reset()                    { *m = Int64{} }
func (m *Int64) String() string            { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()               {}
func (*Int64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Int64) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Int64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Int64) GetNegation() bool {
	if m != nil {
		return m.Negation
	}
	return false
}

func (m *Int64) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_NULL
}

// Uint64 ...
type Uint64 struct {
	Values   []uint64  `protobuf:"varint,1,rep,packed,name=values" json:"values,omitempty"`
	Valid    bool      `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Negation bool      `protobuf:"varint,3,opt,name=negation" json:"negation,omitempty"`
	Type     QueryType `protobuf:"varint,4,opt,name=type,enum=qtypes.QueryType" json:"type,omitempty"`
}

func (m *Uint64) Reset()                    { *m = Uint64{} }
func (m *Uint64) String() string            { return proto.CompactTextString(m) }
func (*Uint64) ProtoMessage()               {}
func (*Uint64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Uint64) GetValues() []uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Uint64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Uint64) GetNegation() bool {
	if m != nil {
		return m.Negation
	}
	return false
}

func (m *Uint64) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_NULL
}

// Float64 ...
type Float64 struct {
	Values   []float64 `protobuf:"fixed64,1,rep,packed,name=values" json:"values,omitempty"`
	Valid    bool      `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Negation bool      `protobuf:"varint,3,opt,name=negation" json:"negation,omitempty"`
	Type     QueryType `protobuf:"varint,4,opt,name=type,enum=qtypes.QueryType" json:"type,omitempty"`
}

func (m *Float64) Reset()                    { *m = Float64{} }
func (m *Float64) String() string            { return proto.CompactTextString(m) }
func (*Float64) ProtoMessage()               {}
func (*Float64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Float64) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Float64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Float64) GetNegation() bool {
	if m != nil {
		return m.Negation
	}
	return false
}

func (m *Float64) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_NULL
}

// Timestamp ...
type Timestamp struct {
	Values   []*google_protobuf.Timestamp `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	Valid    bool                         `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Negation bool                         `protobuf:"varint,3,opt,name=negation" json:"negation,omitempty"`
	Type     QueryType                    `protobuf:"varint,4,opt,name=type,enum=qtypes.QueryType" json:"type,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Timestamp) GetValues() []*google_protobuf.Timestamp {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Timestamp) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Timestamp) GetNegation() bool {
	if m != nil {
		return m.Negation
	}
	return false
}

func (m *Timestamp) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_NULL
}

func init() {
	proto.RegisterType((*String)(nil), "qtypes.String")
	proto.RegisterType((*Int64)(nil), "qtypes.Int64")
	proto.RegisterType((*Uint64)(nil), "qtypes.Uint64")
	proto.RegisterType((*Float64)(nil), "qtypes.Float64")
	proto.RegisterType((*Timestamp)(nil), "qtypes.Timestamp")
	proto.RegisterEnum("qtypes.QueryType", QueryType_name, QueryType_value)
}

func init() { proto.RegisterFile("qtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x4b, 0x6b, 0xdb, 0x4e,
	0x14, 0xc5, 0xff, 0xf2, 0x43, 0x96, 0xae, 0xfc, 0x18, 0xdf, 0x84, 0x3f, 0xc2, 0x9b, 0x1a, 0x43,
	0xc1, 0x74, 0xa1, 0x80, 0x5b, 0xba, 0x97, 0xdb, 0xb1, 0x23, 0x50, 0x26, 0x8e, 0x66, 0xd4, 0x26,
	0xdd, 0x08, 0x85, 0xaa, 0x46, 0xe0, 0x48, 0xae, 0x25, 0x9b, 0xba, 0x9f, 0xa4, 0xd0, 0x0f, 0xd2,
	0xaf, 0x57, 0x46, 0x0f, 0xd3, 0xd7, 0xd6, 0x3b, 0xfd, 0xce, 0x3d, 0x33, 0xe7, 0x80, 0x2e, 0x03,
	0xdd, 0xcf, 0xf9, 0x71, 0x1b, 0x65, 0xd6, 0x76, 0x97, 0xe6, 0x29, 0xaa, 0x25, 0x8d, 0x9e, 0xad,
	0xd3, 0x74, 0xbd, 0x89, 0xae, 0x0a, 0xf5, 0x71, 0xff, 0xe9, 0x2a, 0x8f, 0x9f, 0xa2, 0x2c, 0x0f,
	0x9f, 0xb6, 0xa5, 0x71, 0xf2, 0x5d, 0x01, 0x95, 0xe7, 0xbb, 0x38, 0x59, 0xe3, 0xff, 0xa0, 0x1e,
	0xc2, 0xcd, 0x3e, 0xca, 0x4c, 0x65, 0xdc, 0x9c, 0xea, 0x5e, 0x45, 0x78, 0x09, 0xed, 0x43, 0xb8,
	0x89, 0x3f, 0x9a, 0x8d, 0xb1, 0x32, 0xd5, 0xbc, 0x12, 0x70, 0x04, 0x5a, 0x12, 0xad, 0xc3, 0x3c,
	0x4e, 0x13, 0xb3, 0x59, 0x0c, 0x4e, 0x8c, 0xcf, 0xa1, 0x25, 0xe3, 0xcd, 0xd6, 0x58, 0x99, 0xf6,
	0x67, 0x43, 0xab, 0xaa, 0x76, 0xb7, 0x8f, 0x76, 0x47, 0x71, 0xdc, 0x46, 0x5e, 0x31, 0xc6, 0x31,
	0x18, 0x71, 0x92, 0x45, 0x49, 0x16, 0xe7, 0xf1, 0x21, 0x32, 0xdb, 0xc5, 0x2d, 0xbf, 0x4a, 0x93,
	0x2f, 0xd0, 0x76, 0x92, 0xfc, 0xf5, 0xab, 0x3f, 0xba, 0x35, 0xcf, 0xde, 0x6d, 0x72, 0x04, 0xd5,
	0x8f, 0xff, 0x11, 0xdd, 0x3a, 0x7f, 0xf4, 0x57, 0xe8, 0x2c, 0x36, 0x69, 0xf8, 0x77, 0xb6, 0x72,
	0xfe, 0xec, 0x6f, 0x0a, 0xe8, 0xa2, 0x5e, 0x11, 0x9c, 0xfd, 0x16, 0x6f, 0xcc, 0x46, 0x56, 0xb9,
	0x4e, 0x56, 0xbd, 0x4e, 0xd6, 0xc9, 0x7b, 0xf6, 0x6a, 0x2f, 0x7e, 0x34, 0x40, 0x3f, 0x69, 0xa8,
	0x41, 0x8b, 0xf9, 0xae, 0x4b, 0xfe, 0x43, 0x1d, 0xda, 0xf4, 0xce, 0xb7, 0x5d, 0xa2, 0xa0, 0x01,
	0x9d, 0xa5, 0x47, 0x6d, 0x41, 0x3d, 0xd2, 0xc0, 0x21, 0xf4, 0x2a, 0x08, 0xca, 0x79, 0x53, 0x1e,
	0x72, 0x29, 0xe7, 0xa4, 0x85, 0x7d, 0x00, 0xf9, 0x55, 0x4d, 0xda, 0xa8, 0x42, 0xc3, 0x61, 0x44,
	0x95, 0x37, 0xcc, 0xa9, 0x78, 0x4f, 0x29, 0x23, 0x1d, 0x69, 0xba, 0xb6, 0x79, 0xb0, 0xf2, 0xe8,
	0xc2, 0xb9, 0x27, 0x5a, 0xcd, 0xdc, 0x5f, 0x48, 0xd6, 0xb1, 0x07, 0x3a, 0xf7, 0xe7, 0x5c, 0x78,
	0x0e, 0x5b, 0x12, 0x90, 0x67, 0x57, 0xb6, 0x10, 0xd4, 0x63, 0xc4, 0x90, 0xde, 0x1b, 0x87, 0x05,
	0x2e, 0x65, 0x4b, 0x71, 0x4d, 0xba, 0x05, 0xdb, 0xf7, 0x35, 0xf7, 0xa4, 0xf9, 0xf6, 0x1d, 0xf5,
	0x5c, 0x7b, 0x45, 0xfa, 0xd8, 0x05, 0xed, 0xcd, 0x2d, 0x13, 0xb6, 0xc3, 0x38, 0x19, 0xe0, 0x05,
	0x0c, 0x1c, 0x1e, 0x54, 0x02, 0x7d, 0x1b, 0xcc, 0x1f, 0x08, 0xc1, 0x01, 0x18, 0x32, 0x9b, 0xba,
	0xf4, 0x86, 0x32, 0x41, 0x86, 0xd2, 0x25, 0x05, 0x9b, 0x3d, 0x9c, 0x44, 0xc4, 0x4b, 0x20, 0x85,
	0xe8, 0xba, 0xb5, 0xc8, 0xc9, 0xc5, 0x5c, 0xfb, 0x50, 0x3d, 0x07, 0x8f, 0x6a, 0xf1, 0xe3, 0x5e,
	0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x0b, 0x34, 0x2c, 0x2d, 0x04, 0x00, 0x00,
}
